version: "3.9"

services:
  postgres_db:
    image: postgres:17.2-alpine
    container_name: database
    ports:
      - 5432:5432
    networks:
      myAppNetwork:
        aliases:
          - pghost
    volumes:
      - ~/apps/pg_db:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL","sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
  myapp:
    build: .
    container_name: "backend"
    ports:
      - 8080:8080
    expose:
      - 8080
    env_file: .env
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - myAppNetwork
    command: ["/app/wait-for-it.sh", "pghost:5432", "--","sh", "-c", "/app/run-all.sh 2>&1 | tee serverlogs_$(date '+%Y-%m-%d-%H').log"]
    volumes:
      - .\logs:./logs
networks:
  myAppNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
volumes:
  logs:
    driver: local