version: "3.9"

services:
  postgres_db:
    image: postgres:latest
    container_name: pg_db
    ports:
      - 5432:5432
    volumes:
      - ~/apps/pg_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=SECRET
      - POSTGRES_USER=pguser
      - POSTGRES_DB=pg_db
