version: "3.9"

services:
  postgres_db:
    image: postgres:17.2-alpine
    container_name: database
    ports:
      - 5432:5432
    networks:
      myAppNetwork:
        aliases:
          - pghost
    volumes:
      - ./.localdb:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL","sh -c 'pg_isready -U ${DB_USER} -d ${DB_DATABASE}'"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
  myapp:
    build:
      context: .
    container_name: "backend"
    ports:
      - 8080:8080
    expose:
      - 8080
    env_file: .env
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - myAppNetwork
    command: ["/app/wait-for-it.sh", "${DB_HOST}:${DB_PORT}", "--","sh", "-c", "/app/run-all.sh 2>&1 | tee /app/logs/serverlogs_$(date '+%Y-%m-%d-%H').log"]
    volumes:
      - ./logs:/app/logs
networks:
  myAppNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
